spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.2.104/sell?characterEncoding=utf-8&useSSL=false
     username: root
     password: 123456
     type: com.alibaba.druid.pool.DruidDataSource
  hikari:
     max-lifetime: 5000
     maximum-pool-size: 150
     idle-timeout: 6000
     connection-timeout: 6000
     validation-timeout: 3000
     login-timeout: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml


server:
 context-path: /sell
 port: 8080


#日志的配置方式：1.在application中如下配置；2.在logback-spring.xml中进行配置
#logging:
#  pattern:
#  console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#  com.imooc.LoggerTest: debug